# Generated by Django 2.2 on 2019-04-18 19:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0012_auto_20190125_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='timestamp',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
