# Generated by Django 2.2 on 2019-04-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0013_auto_20190418_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='timestamp',
            field=models.DateField(auto_now_add=True),
        ),
    ]
